# Default initial positions for rover_robot's ros2_control fake system

initial_positions:
  Claw1_link_joint: 0
  Claw2_link_joint: 0
  Scara1_link_joint: 0
  Scara2_link_joint: 0
  Scara3_link_joint: 0
  Scara4_link_joint: 0